apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- route.yaml
images:
#- name: ghcr.io/shclub/edu12-frontend
- name: ghcr.io/dragorse/edu12-frontend
  newTag: "20230326152802"
